-- 1. Search History Table
CREATE TABLE IF NOT EXISTS search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT DEFAULT 'anonymous',
    education TEXT,
    target_career TEXT,
    selected_path TEXT,
    experience_level TEXT,
    career_fit_score INTEGER,
    hiring_probability INTEGER,
    growth_potential INTEGER,
    risk_level TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Decision History Table
CREATE TABLE IF NOT EXISTS decision_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT DEFAULT 'anonymous',
    option_a TEXT,
    option_b TEXT,
    recommended_choice TEXT,
    comparison_result TEXT,
    impact_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Saved Reports Table
CREATE TABLE IF NOT EXISTS saved_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT DEFAULT 'anonymous',
    final_best_path TEXT,
    career_growth_score INTEGER,
    roadmap_summary TEXT,
    recommendations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add some indices for faster querying
CREATE INDEX idx_search_history_user ON search_history(user_id);
CREATE INDEX idx_decision_history_user ON decision_history(user_id);
CREATE INDEX idx_saved_reports_user ON saved_reports(user_id);
